### ISSUE TITLE
"lucasazzola.vscode-levels": Line 1: Unexpected token.

### ISSUE THREAD

**Issue by kurtextrem** [DerFlatulator/vscode-levels#1]
[Extension Host] Activating extension `lucasazzola.vscode-levels` failed:  Line 1: Unexpected token
d.logExtensionHostMessage @ extensionHost.ts:285
extensionHost.ts:285 [Extension Host] Here is the error stack:  Error: Line 1: Unexpected token
    at ErrorHandler.constructError (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:3396:22)
    at ErrorHandler.createError (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:3414:27)
    at Parser.unexpectedTokenError (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:542:39)
    at Parser.tolerateUnexpectedToken (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:555:42)
    at Parser.parseStatementListItem (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:1801:31)
    at Parser.parseProgram (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:3061:29)
    at Object.parse (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\esprima\dist\esprima.js:117:24)
    at sourceCodeToAst (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\out\src\extension.js:27:43)
    at C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\node_modules\lodash\lodash.js:5157:35
    at apply (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\out\src\extension.js:41:24)
    at Array.forEach (native)
    at activate (C:\Users\admin\.vscode-insiders\extensions\lucasazzola.vscode-levels-0.1.1\out\src\extension.js:10:40)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:373051)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:372836)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:372611
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:62432)

**Comment by azz** [comment]
This means the extension was unable to parse your JavaScript. This extension is in very early stages. Error handling needs work. 😄
